# Generated by Django 5.0.6 on 2024-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_rename_portflio_userprofileinfo_portflio_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portflio_site',
            new_name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
